### PR TITLE
Use SLF4J API instead of common-logging

### PR DESCRIPTION
**Pull request by zackehh**
This should resolve issues people were seeing with logging. It keeps using log4j, but via slf4j.

### CODE REVIEW

**Comment by zackehh** [comment]
@dadoonet do you have any time to review this? :)

**Comment by dadoonet** [comment]
Thanks @zackehh for the PR and the heads up. I merged it with some minor changes (94684694907c1ee474bc9beaa33846618078dd4f) and added another commit (a20e94782ac79004f01c1fe773a78ce68522799e).

**Comment by zackehh** [comment]
@dadoonet awesome! Thanks :)

**Comment by harrygu** [comment]
Thank you both very much for getting this change in! @dadoonet, when would you plan to cut a release so it can be pulled directly from Maven?

**Comment by dadoonet** [comment]
2.1.0 has been released. Can't you get it?

**Comment by harrygu** [comment]
That worked. Thanks!

**Comment by dadoonet** [comment]
Awesome! Thanks for confirming!

**Pull request closed without merging**
