### PR TITLE
Expose the High Level REST Client

### LINKED ISSUE #122: Expose the High Level REST Client
In #115 we exposed the Low Level REST Client.
We want to actually expose the High Level REST Client we this one will be released.

### PR DESCRIPTION
**Pull request by dadoonet**
In #115 we exposed the Low Level REST Client.
We want to actually expose the High Level REST Client when this one will be released.

Closes #122.

### CODE REVIEW

**Comment by dadoonet** [comment]
@nithril Could you have a look at this branch? I can't make the async mode working well with the High Level Rest client as you can see in the latest commit.

Should I remove this async feature for the REST Client? Or do you think there is a way to fix that?

Thanks!

**Comment by nithril** [comment]
Do you think the async feature is worth it?

**Comment by dadoonet** [comment]
Nope. But you asked for it in the first place. 😉 

So I prefer asking before removing.

**Comment by nithril** [comment]
Thanks for asking :). I agree the REST client definitively removes the need of an async feature.

**Pull request merged**
